### ISSUE TITLE
`iroh store remove` command

### ISSUE THREAD

**Issue by b5** [n0-computer/beetle#110]
A command for removing a CID from the store. We may need to implement caching first? Or maybe CID removal just removes the CID for now.

### Tasks
- [ ] Plan remove command
- [ ] write initial documentation
- [ ] make it work
- [ ] tests
